# Title of the document
title: "Pandas Profiling Report"

# Metadata
dataset:
  description: "Swing Stats based on Foresight Sports Launch Monitor"
  creator: "Fran Sky Bailey"
  author: "F. Jeb"
  copyright_holder: ""
  copyright_year: "5.11.2021"
  url: "golfocean.gq"

variables:
  descriptions: {}

# infer dtypes
infer_dtypes: False

# Show the description at each variable (in addition to the overview tab)
show_variable_description: False

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Show the progress bar
progress_bar: True

# Per variable type description settings
vars:
    num:
        quantiles:
              - 0.05
              - 0.25
              - 0.5
              - 0.75
              - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 5
# Set to zero to disable
        chi_squared_threshold: 0.0
    cat:
        length: False
        characters: False
        words: False
        cardinality_threshold: 50
        n_obs: 5
# Set to zero to disable
        chi_squared_threshold: 0.0
        coerce_str_to_date: False
        redact: False
        histogram_largest: 10
    bool:
        n_obs: 3
# string to boolean mappings pairs (true, false)
        mappings:
          - ["t", "f"]
          - ["yes", "no"]
          - ["y", "n"]
          - ["true", "false"]
    path:
        active: False
    file:
        active: False
    image:
        active: False
        exif: False
        hash: False
    url:
        active: False


# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: None

# which diagrams to show
missing_diagrams:
    bar: False
    matrix: False
    heatmap: False
    dendrogram: False

correlations:
    pearson:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    spearman:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    kendall:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    phi_k:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    cramers:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9


# Bivariate / Pairwise relations
interactions:
  targets: []
  continuous: True

# For categorical
categorical_maximum_correlation_distinct: 100

# Plot-specific settings
plot:
# Image format (svg or png)
    image_format: "svg"
    dpi: 800

    scatter_threshold: 1000

    correlation:
        cmap: 'RdBu'
        bad: '#000000'

    missing:
        cmap: 'RdBu'
# Force labels when there are > 50 variables
# https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615
        force_labels: True

    pie:
# display a pie chart if the number of distinct values is smaller or equal (set to 0 to disable)
      max_unique: 0

    histogram:
        x_axis_labels: True

# Number of bins (set to 0 to automatically detect the bin size)
        bins: 50

# Maximum number of bins (when bins=0)
        max_bins: 250

# The number of observations to show
n_obs_unique: 5
n_extreme_obs: 5
n_freq_table_max: 10

# Use `deep` flag for memory_usage
memory_deep: False

# Configuration related to the duplicates
duplicates:
    head: 0
    key: "# duplicates"

# Configuration related to the samples area
samples:
    random: 5
    head: 0
    tail: 0

# Configuration related to the rejection of variables
reject_variables: True

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'
# or 'src'
        attribute: 'srcdoc'

html:
# Minify the html
    minify_html: True

# Offline support
    use_local_assets: True

# If True, single file, else directory with assets
    inline: True

# Show navbar
    navbar_show: True

# For internal use
    file_name: None

# Styling options for the HTML report
    style:
      theme: flatly
      logo: ""
      primary_color: "#1b002b"
      full_width: False